name: Quality

on:
  pull_request:
    paths:
      - 'pydocstyle_gitlab_code_quality/**'
      - 'ci_requirements.txt'
      - 'pyproject.toml'

jobs:
  pylint:
    name: Python ${{ matrix.python_version }} - pylint check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install_dependencies
        with:
            python_version: ${{ matrix.python_version }}
      - name: Run pylint
        run: |
          pylint --output-format=colorized $(git ls-files '*.py')
  mypy:
    name: Python ${{ matrix.python_version }} - mypy check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install_dependencies
        with:
          python_version: ${{ matrix.python_version }}
      - name: Run mypy
        run: |
          mypy --config-file pyproject.toml .
  isort:
    name: Python ${{ matrix.python_version }} - isort check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install_dependencies
        with:
          python_version: ${{ matrix.python_version }}
      - name: Run isort
        run: |
          isort --settings-file pyproject.toml --check --diff --color .
  black:
    name: Python ${{ matrix.python_version }} - black check
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python_version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/install_dependencies
        with:
          python_version: ${{ matrix.python_version }}
      - name: Run black
        run: |
          black --config pyproject.toml --check --diff --color .
