name: Release to PyPi

on:
  release:
    types: [published]

jobs:
  publish_to_pypi:
    name: Publish package to PyPi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install build and publish dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install build twine
      - name: Build package
        shell: bash
        run: |
          python -m build
      - name: Publish to PyPi
        shell: bash
        run: |
          python -m twine upload --non-interactive --username ${{ secrets.PYPI_USERNAME }} --password ${{ secrets.PYPI_PASSWORD }} --repository pypi dist/*
